name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
categories:
  - title: "🚀 Features"
    labels: ["feat"]
  - title: "🐛 Bug Fixes"
    labels: ["fix"]
  - title: "🛠 Maintenance"
    labels: ["chore", "refactor", "perf"]
  - title: "📝 Documentation"
    labels: ["docs"]
  - title: "⚡ Other Changes"
    labels: ["test", "ci"]
autolabeler:
  - label: "feat"
    title: ["/feat/i"]
    branch: ["/^feat/i"]
  - label: "fix"
    title: ["/fix/i"]
    branch: ["/^fix/i"]
  - label: "chore"
    title: ["/chore/i"]
    branch: ["/^chore/i"]
  - label: "docs"
    title: ["/docs/i"]
    branch: ["/^docs/i"]
  - label: "refactor"
    title: ["/refactor/i"]
    branch: ["/^refactor/i"]
  - label: "perf"
    title: ["/perf/i"]
    branch: ["/^perf/i"]
  - label: "test"
    title: ["/test/i"]
    branch: ["/^test/i"]
  - label: "ci"
    title: ["/ci/i"]
    branch: ["/^ci/i"]
template: |
  ## Changes

  $CHANGES