template: |
  ## Changes

  $CHANGES
name-template: 'v$RESOLVED_VERSION ðŸŒˆ'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
categories:
  - title: "ðŸš€ Features"
    labels: ["feat"]
  - title: "ðŸ› Bug Fixes"
    labels: ["fix"]
  - title: "ðŸ›  Maintenance"
    labels: ["chore", "refactor", "perf"]
  - title: "ðŸ“ Documentation"
    labels: ["docs"]
  - title: "âš¡ Other Changes"
    labels: ["test", "ci", "build"]
autolabeler:
  - label: "feat"
    title: ["/^feat/i"]
    body: ["/^feat/i"]
    branch: ["/^feat/i"]
  - label: "fix"
    title: ["/^fix/i"]
    body: ["/^fix/i"]
    branch: ["/^fix/i"]
  - label: "chore"
    title: ["/^chore/i"]
    body: ["/^chore/i"]
    branch: ["/^chore/i"]
  - label: "docs"
    title: ["/^docs/i"]
    body: ["/^docs/i"]
    branch: ["/^docs/i"]
  - label: "refactor"
    title: ["/^refactor/i"]
    body: ["/^refactor/i"]
    branch: ["/^refactor/i"]
  - label: "perf"
    title: ["/^perf/i"]
    body: ["/^perf/i"]
    branch: ["/^perf/i"]
  - label: "test"
    title: ["/^test/i"]
    body: ["/^test/i"]
    branch: ["/^test/i"]
  - label: "ci"
    title: ["/^ci/i"]
    body: ["/^ci/i"]
    branch: ["/^ci/i"]
  - label: "build"
    title: ["/^build/i"]
    body: ["/^build/i"]
    branch: ["/^build/i"]
